function export2pdf(figh, fn, pp, fontsize, openpdf)
% EXPORT2PDF - Export the figure to PDF format
% figh: name of figure handle
% pp  : paperposition: array
% fn  : filename
% fontsize: fontsize of the texts
% openpdf : a logical input to decide on opening the output PDF file

    % Fetch the path information of the calling script.
    [ST,~] = dbstack('-completenames');
    if length(ST)==1
        % The figure is opened in Matlab console.
        filepath = get(figh,'FileName');
    else
        % The figure is generated by an m-file.
        filepath = ST(2).file;
    end

    [pathstr, name, ~] = fileparts(filepath);

    if isempty(pathstr)
        % In case this is a new figure and has not been saved.
        pathstr = pwd;
    end
    pathstr = [pathstr, '/'];

    % check the input argumetns
    if nargin < 1
        error('***ERROR: There are not enough input arguments!');
    end
    if nargin < 2 || isempty(fn)
        fn = name;
    end
    if nargin < 3
        pp = [0 0 20 14];
    end
    if nargin < 4 || isempty(fontsize)
        fontsize = 10;
    end
    if nargin < 5 || isempty(openpdf)
        openpdf=false;
    end
    if nargin > 5
        error('***ERROR: There are too many input arguments!');
    end

    % Print the figure.
    set(findall(gcf,'type','axes'),'Fontsize',fontsize);
    set(findall(gcf,'type','text'),'FontSize',fontsize);

    set(figh,'PaperUnits','centimeters', ...
             'PaperPositionMode','manual', ...
             'PaperPosition',pp, ...
             'PaperSize',pp(3:4));
    output_eps = [pathstr,fn,'.eps'];
    output_pdf = [pathstr,fn,'.pdf'];
    print('-depsc2',output_eps);

%     % Convert the EPS file to the PDF file.
%     system(['epstopdf ', output_eps, ' && rm ', output_eps]);
% 
%     % Open the PDF file.
%     if openpdf == true
%         system(['acroread ', output_pdf, ' &']);
%     end
end
